name: CI Pipeline

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: --health-cmd="curl --silent --fail localhost:27017 || exit 1" --health-interval=6m --health-timeout=5s --health-retries=10

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Lint Code
        run: npm run lint
